name: Deploy
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Check package version
        id: cpv
        uses: PostHog/check-package-version@v2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci
          
      - name: Build Storybook
        run: npm run build
          
      - name: Modify Permissions-Policy header
        run: |
          echo "permissions-policy: interest-cohort=()" >> $GITHUB_WORKSPACE/storybook-static/CNAME

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./storybook-static
          branch: gh-pages
          clean: true
          clean-exclude: pr:**/*
